README.md

- Add links to all Marketplace applications to README.md
- Fix typo

JCS-13699 Add links to the marketplace offerings in README.md in github

---

terraform/modules/compute/wls_compute/wls_compute.tf

Add data & mw ocids details to instance metadata.
This is required to fetch the Block volume information using Volume ocids during volume mounting.

Add data & mw ocids to instance metadata

---

terraform/locals.tf

Implemented [JCS-13864] - Allow namespace in OCIR Registry User Name
Note: This change is using terraform 0.12 compatible string handling functions.
TEST: PASS.  
Stack Variable: **ocir_user =  ax8cfrmecktw/oracleidentitycloudservice/harshad.vilekar@oracle.com**
1. PASS: stack apply succeeded with autoscaling
2. PASS: metatada verification
"ocir_user": "ax8cfrmecktw/oracleidentitycloudservice/harshad.vilekar@oracle.com",

fix JCS-13864 Allow namespace in OCIR Registry User Name

---

builds/build_cli.sh
terraform/main.tf
terraform/modules/validators/stack_validators.tf
terraform/modules/validators/variables.tf

Issue Fixed:
- [JCS-13837](https://jira.oraclecorp.com/jira/browse/JCS-13837) Enh 35251378 - Script to check existing stack prefix before provisioning
Validation:
- The validation fails if another stack with the service name is already present in the same stack compartment
Limitations:
- Only the stacks in the current stack compartment are checked. Other compartments are not checked. 
- Validation is done for UI mode only. No validation is done for CLI mode.
Tests PASS: 
- PASS: create second stack with the same prefix in the same compartment, and verify the apply fails with the validation error. 
- PASS: validation succeeds if there is no other stack with the same service_name in the same compartment
- PASS: destroy fails

add validation to check existing stack prefix before provisioning

---

terraform/modules/compute/wls_compute/locals.tf

Fix the connection string provisioning issues
1. Created JRF instance with rac database without providing db connecting string.
2. Created JRF instance with rac database with providing db connect string.

Fix the jira 13945

---

terraform/modules/compute/wls_compute/locals.tf

Fix the connection string provisioning issues
1. Created JRF instance with rac database without providing db connecting string.
2. Created JRF instance with rac database with providing db connect string.
(cherry picked from commit a41ddb07e0b6bb156f493b189afd178cee96073f)

Fix the jira 13945 (#216)

---

terraform/modules/lb/backends/lb_backends.tf

Fixed bug Certificate on LB is reset in scaling operation.
Test
-----
Create a single VM instance with load balancer.
Create a new certificate to the load balancer.
Note that you can generate a keypair from any OCI compute instance with 'openssl req -new -sha256 -newkey rsa:2048 -nodes -keyout testssl.key -x509 -days 365 -out testssl.crt'
Note that you'll need to add both the certificate and private key pems that are generated to the certificate.
Associate the certificate you added to the listener for the load balancer.
Delete the demo certificate that was generated by the Stack from the load balancer.
Edit the stack and add a node.
Make sure that new certificate is assigned to the listener.
Demo certificate will be recreated but not assigned to any.
The certificate created and added by a …

Fix bug Certificate on LB is reset in scaling operation

---

terraform/modules/validators/oci_db_validators.tf
terraform/schema.yaml

Bug - Fail to get password expiry date for OPSS user when using connect string
Note that since the DB service name is not guaranteed to include the PDB name ( I proved this by using a connect string w/o the PDB name in it to successfully create a WLS for OCI instance). Therefore, the PDB name must be asked for.
Also note that the validation change added will not be executed, but to limit the scope of the changes I updated the validation only and didn't try to also add in the validator. I suspect that the validation was never added in order to ensure that 11g databases, which don't have a PDB can be allowed.
Tested that when setting a connect string the error occurred. After the fix, with PDB name provided, the error did not occur.

JCS-14035 - Fail to get password expiry date when using connect string

---

terraform/main.tf

validate_vcn_cidr.py always returning errors in bootstrap log due to wls_vcn_cidr being empty with existing subnets.
Note that this is essentially a revert to the previous commit. The checkin log for the commit states, "Use customer provided NSGs for existing subnet provisioning". Therefore, I tested with existing subnet and NSGs provided with the reversion of this line change and there were no issues. Other tests in addition to existing subnet with NSGs provided:
1. New VCN.
2. Existing VCN, new subnet
3. Existing subnet with security rules. In each case I tested with IDCS added so the call to validate_vcn_cidr.py would occur. I not only made sure the error no longer appeared, but verified that the metadata value was present and ran validate_vcn_cidr.py by hand.

JCS-13959 - validate_vcn_cidr.py always returning errors in bootstrap

---

terraform/modules/policies/locals.tf

Verified issue by creating stack in a compartment without dynamic group policies set and selecting OCI Policies checkbox. Clicked on Instances|Instance Details and navigate to the OS Management and saw:
"No OS management information is available for this resource."
After fix ran same test and OS Managment information appears.

JCS-14038 - Missing OSMS agent required dynamic-group policies

---

terraform/modules/compute/wls_compute/validators.tf
terraform/schema.yaml
terraform/schema_14110.yaml

JCS-14046 Support VM.Standard.E5.Flex shape, but not as default shape.
Testing using E5.Flex shape (requires OL8.8 image):
- 14.1.1.0 JDK11 with IDCS. idcs-sample-app logged into.
- 12.2.1.4 JRF on ATP with IDCS (2 OCPU count). idcs-sample-app logged into.
- 14.1.1.0 JDK8 with IDCS validated cloning.
Testing max cpu utilization (E5.Flex allows 94 ocpu max):
- Using same logic changes in this MR built stack with:
-- max OCPUs for Flex5 to 1
-- max OCPUs for Flex4 to 2
-- Set 2 OCPUs for Flex 5 and ran tf plan. Confirmed validation error fired.
-- Set 3 OCPUs for Flex 4 and ran tf plan. Confirmed validation error fired. This shows no regression in the logic changes.

JCS-14046 Support VM.Standard.E5.Flex shape, but not as default shape.

---

terraform/modules/provisioners/provisioning.tf
terraform/modules/provisioners/variables.tf

JCS-14023 Status check missing from public subnet provisioning
Verified status check now showing for public subnet, private endpoint and bastion still showing status check, and that private subnet w/o bastion still does not attempt to get status check. Verified all conditions using both ORM UI and CLI.

JCS-14023 Status check missing from public subnet provisioning

---

terraform/locals.tf
terraform/main.tf
terraform/modules/compute/wls_compute/wls_compute.tf
terraform/modules/compute/wls_compute/wls_variables.tf
terraform/modules/validators/validators.tf
terraform/modules/validators/variables.tf
terraform/schema.yaml
terraform/schema_14110.yaml
terraform/weblogic_variables.tf

**Testing**
1. Additional admin user added in the UI with the default username as 'wls_user_1'.
2. Usernames 'weblogic' and 'administrator' are blocked in UI, while 'weblogic1' works fine.
3. Username 'weblogic' is blocked in terraform.

Set two weblogic users in the Admin role in WLS for OCI

---

terraform/main.tf
terraform/modules/lb/backends/lb_backends.tf
terraform/modules/lb/backends/variables.tf

This MR is to configure OCI Load Balancer Backend Set to use SSL
Testing results are uploaded to associated jira https://jira.oraclecorp.com/jira/browse/JCS-14325

Configure OCI Load Balancer backend set to use SSL

---

terraform/modules/compute/wls_compute/wls_compute.tf
terraform/modules/compute/wls_compute/wls_volume.tf

- Make the keys of the maps of compute and volumes resources to have 2 digits at the end, to conserve the iteration order, which is lexicographical, to prevent volume attachments from being reassigned to other instances because of the iteration order in the list of compute instances
Tests:
- Created a non-JRF stack with new VCN, and two nodes
- Scaled up the stack to 4 nodes, verified the apply job completed successfully and that all servers were added.
- Scaled up the stack to 10 nodes, and verified the same points above
- Scaled up the stack to 11 nodes, and made the same verifications above, and verified that the existing block volume attachments and block volumes where not affected 
- Scaled up the stack to 20 nodes, and made the same verifications above
- Scaled up the stack to 30 …

JCS-14392 -  Issue with volume attachments on scale-out

---

terraform/modules/network/vcn-config/nsg_security_rule.tf

Apply job succeeded for 2 node provisioning
Modified the secrule from managed server NSG which now opens for administration port 9002 instead of all ports for wls subnet cidr in case of secured production mode

JCS-14388 - Implementation: Remove the secrule from managed server NSG which opens all ports for wls subnet cidr.

---

terraform/locals.tf
terraform/main.tf
terraform/modules/compute/wls_compute/variables.tf
terraform/modules/compute/wls_compute/wls_compute.tf
terraform/modules/policies/locals.tf
terraform/modules/policies/variables.tf
terraform/modules/validators/validators.tf
terraform/modules/validators/variables.tf
terraform/schema.yaml
terraform/schema_14110.yaml
terraform/weblogic_variables.tf

https://jira.oraclecorp.com/jira/browse/JCS-14449

Changes related to Certificate validity & ORM UI

---

terraform/modules/validators/validators.tf
terraform/schema.yaml

https://jira.oraclecorp.com/jira/browse/JCS-14477
Testing
========
**Show that the ORM UI in 12.2.1.4 does not show the JRF option when secured production mode is enabled.**
**Execute the CLI with variable contents that would indicate JRF usage and secured production mode enabled and show that validation error is raised.**
**With ATP-DB variables:**
**With OCI-DB variables:**

Disable JRF for secured production mode

---

terraform/main.tf
terraform/modules/network/vcn-config/nsg_security_rule.tf
terraform/modules/network/vcn-config/variables.tf
terraform/weblogic_variables.tf

This MR is to open port 9072 for weblogic subnet CIDR in managed server NSG in secure mode

Open port 9072 for weblogic subnet in managed server NSG in secure mode

---

terraform/main.tf
terraform/modules/network/vcn-config/nsg_security_rule.tf
terraform/modules/network/vcn-config/variables.tf

Open node manager port in managed server NSG
**Tested 5 node provisioning in secure mode & non-secure mode. updateDomain.sh shows no error in provisioning logs**

Open node manager port in managed server NSG

---

terraform/autoscaling_variables.tf
terraform/main.tf
terraform/modules/observability/autoscaling/monitoring_alarms.tf
terraform/modules/observability/autoscaling/variables.tf
terraform/schema.yaml
terraform/schema_14110.yaml

The monitoring alarm is being created as enabled only when the option "Create OCI policies" checkbox is selected. The problem seems to be in monitoring_alarms.tf line 11 because the flag "is_enabled" is associated directly to var.create_policies which doesn't make sense. This PR is to add a new variable independent to var.create_policies so when customer clear the "Create OCI policies" checkbox the alarms created for autoscaling remain enabled.
This option is intentionally hidden to the customer as we don't have a use case for customers to create autoscaling with disabled alarms and these are defaulted to true. The variables are configured in case of advanced customers who may want to customize the stack can easily override those variables.
Testing with OCI Checkbox enabled:
-     Verify …

Add new flag for autoscaling alarm state defaulted to true

---

terraform/modules/compute/wls_compute/idcs_variables.tf

Update IDCS appgateway to 23.4.44-2310291619. This container image version in 23.4.44 changed to idcs-appgateway-docker.
Tested multi-node 12.2.1.4 and 14.1.1.0 in secured production mode and non-secured production mode by accessing IDCS sample app.

JCS-14499 - Use the latest IDCS appgateway 23.4.44

---

terraform/modules/policies/locals.tf

JCS-14582 - WLS for OCI dynamic group policy for instances does not allow volumes to be added to the instance. This causes issues for cloning scripts when volumes need to be added and removed from the instances using the OCI API. Verified by creating a WLS for OCI instance with "OCI Polcies" checkbox enabled and cloning that instance.

JCS-14582 - Manage instances in dynamic group policies

---

terraform/variables.tf

Set is_rms_private_endpoint_required to true by so CLI users do not have to set this to false. Since a true value is only relevant to ORM execution the default of true was causing issues for CLI users. Verified that default value of false in terraform while ORM UI YAMLs have a default true does not cause any regressions.

JCS-14565 - Default is_rms_private_endpoint_required to true

---

terraform/main.tf
terraform/modules/compute/wls_compute/variables.tf
terraform/modules/compute/wls_compute/wls_compute.tf
terraform/modules/compute/wls_compute/wls_volume.tf
terraform/network_variables.tf
terraform/schema.yaml
terraform/schema_14110.yaml

In the UI show that there is an option to put all the Compute instances in the same AD.
Show that the option is not selected by default. 
check box : **Use Same Availability Domain for all Compute Instances**
Show that if the option is selected in the UI that the Compute instances are all in the same AD.
IDCS instance with this option selected has the IDCS sample app added correctly. 
Show that the backends for the load balancer are set up correctly.
Perform and scale out and show that the additional instance is added in the same AD.
Show that there are no issues with cloning.
Show that there are no issues with autoscaling.
`Apply complete! Resources: 65 added, 0 changed, 0 destroyed.
Outputs:
autoscaling_function_application_id = …

Provide an option to put all the Compute instances in the same AD

---

terraform/schema.yaml
terraform/schema_14110.yaml
terraform/schema_14120.yaml

Issue: Load Balancer NSG not visible in edit stack when add existing NSG is selected.
Before:
=====
After:
===

Fix for Load Balancer NSG not visible in edit stack when add existing NSG is selected

---

terraform/modules/policies/locals.tf
terraform/modules/policies/wlsc_policies.tf

Split policy statements in two due to OCI 50 statement policy limit.

Split policy statements in two due to OCI 50 statement policy limit

---

builds/build_mp_bundles.sh
terraform/images/mp_image_ee_byol.tfvars
terraform/images/mp_image_ee_ucm.tfvars
terraform/images/mp_image_se_byol.tfvars
terraform/images/mp_image_suite_byol.tfvars
terraform/images/mp_image_suite_ucm.tfvars

Fix the mp script to uptake 14.1.2.0 and uptake new image values.

Fix the mp script and uptake image values.

---

terraform/modules/policies/groups.tf
terraform/modules/policies/locals.tf

Ticket: [JCS- 14708](https://jira.oraclecorp.com/jira/browse/JCS-14708)
Changes in the files:
1. `terraform/modules/policies/groups.tf` : Updated a comment (no functional changes).
2. `terraform/modules/policies/locals.tf` : Removed the policy related to OS Management Service Agent.
Tested in both the Ashburn and Phoenix regions, and the policies were created successfully.

JCS-14708: Remove OSMS from WLS for OCI stack

---

terraform/locals.tf
terraform/main.tf
terraform/modules/observability/osmh/versions.tf
terraform/modules/policies/locals.tf
terraform/modules/policies/variables.tf
terraform/modules/validators/validators.tf
terraform/modules/validators/variables.tf
terraform/variables.tf
terraform/versions.tf

Tested with the following scenarios:
- From the OCI console for the policy enhancement
Here, the compartments of both the stack and profile are the same; hence, only one policy is created for OSMH, avoiding duplication.
This is the case where the compartments of the stack and profile are different; hence, two policies are created for accessing OSMH in both the stack and profile compartments.
Terraform CLI changes.
If a stack is created through the Terraform CLI with the default values, OSMH will be enabled by default, since select existing profile defaults to false, a new profile will be created. 
If one needs to select an Existing profile, set the value to true & provide the profile OCID. If the OCID is not provided validation error will be thrown.

Added changes for enhancement in OSMH policies.
