oracle-quickstart/oci-weblogic-server

terraform/images/mp_image_ee_byol.tfvars, terraform/images/mp_image_ee_ucm.tfvars, terraform/images/mp_image_suite_byol.tfvars, terraform/images/mp_image_suite_ucm.tfvars, terraform/mp_variables.tf, terraform/oci_images.tf
Uptake mp image values and bastion image values..
=> Uptake mp image values and bastion images values.

terraform/modules/network-validator/scripts/network_validation.sh
[JCS-13808] - Network validation script fails when using NSGs which have rules with other NSGs as source
Testing is still in progress which I will update in jira.
=> Topic sk jcs 13808

terraform/images/mp_image_ee_byol.tfvars, terraform/images/mp_image_ee_ucm.tfvars, terraform/images/mp_image_se_byol.tfvars, terraform/images/mp_image_suite_byol.tfvars, terraform/images/mp_image_suite_ucm.tfvars
Uptake 23.2.1 listings values which has April PSUS.
=> uptake 23.2.1 mp values.

terraform/images/mp_image_ee_byol.tfvars, terraform/images/mp_image_ee_ucm.tfvars, terraform/images/mp_image_se_byol.tfvars, terraform/images/mp_image_suite_byol.tfvars, terraform/images/mp_image_suite_ucm.tfvars
=> Topic sk merge dev 23.2.1

terraform/main.tf, terraform/network_variables.tf, terraform/schema.yaml, terraform/schema_14110.yaml
Revert network validation script.
=> Revert network validation script.

terraform/main.tf, terraform/network_variables.tf, terraform/schema.yaml, terraform/schema_14110.yaml
Reverted Network validation feature
=> Revert network validation script. (#197)

terraform/images/mp_image_ee_byol.tfvars, terraform/images/mp_image_ee_ucm.tfvars, terraform/images/mp_image_se_byol.tfvars, terraform/images/mp_image_suite_byol.tfvars, terraform/images/mp_image_suite_ucm.tfvars
(cherry picked from commit 1730c412ffaf7991ef7cfe05ba055477c7746525)
=> Uptake mp values.

terraform/images/mp_image_ee_byol.tfvars, terraform/images/mp_image_ee_ucm.tfvars, terraform/images/mp_image_se_byol.tfvars, terraform/images/mp_image_suite_byol.tfvars, terraform/images/mp_image_suite_ucm.tfvars
=> Uptake 23.2.2 image values.

terraform/images/mp_image_ee_byol.tfvars, terraform/images/mp_image_ee_ucm.tfvars, terraform/images/mp_image_se_byol.tfvars, terraform/images/mp_image_suite_byol.tfvars, terraform/images/mp_image_suite_ucm.tfvars
Uptake 23.3.2 marketplace values.
=> Uptake 23.3.2 values.

terraform/images/mp_image_ee_byol.tfvars, terraform/images/mp_image_ee_ucm.tfvars, terraform/images/mp_image_se_byol.tfvars, terraform/images/mp_image_suite_byol.tfvars, terraform/images/mp_image_suite_ucm.tfvars
Uptake marketplace image values into 23.4.3 reelase
=> Topic sk uptake mp 23.4.3

terraform/images/mp_image_ee_byol.tfvars, terraform/images/mp_image_ee_ucm.tfvars, terraform/images/mp_image_se_byol.tfvars, terraform/images/mp_image_suite_byol.tfvars, terraform/images/mp_image_suite_ucm.tfvars
Uptake 24.1.1 marketplace values..
=> Uptake 24.1.1 mp values.

terraform/locals.tf, terraform/main.tf, terraform/modules/compute/wls_compute/variables.tf, terraform/modules/compute/wls_compute/wls_compute.tf, terraform/outputs.tf, terraform/schema.yaml, terraform/schema_14110.yaml, terraform/weblogic_variables.tf
https://jira.oraclecorp.com/jira/browse/JCS-14314
=> Enable secured production mode in WLS for OCI

terraform/modules/compute/wls_compute/variables.tf, terraform/modules/compute/wls_compute/wls_compute.tf
https://jira.oraclecorp.com/jira/browse/JCS-14324
=> Configure the domain to associate Keystores and SSL Certificate using WDT parameters

terraform/locals.tf, terraform/main.tf, terraform/modules/compute/wls_compute/variables.tf, terraform/modules/compute/wls_compute/wls_compute.tf, terraform/modules/network/vcn-config/locals.tf, terraform/modules/network/vcn-config/variables.tf, terraform/schema.yaml, terraform/schema_14110.yaml, terraform/weblogic_variables.tf
https://jira.oraclecorp.com/jira/browse/JCS-14313
=> Enable administration port in WLS for OCI(Secured Production Mode)

terraform/images/mp_image_ee_byol.tfvars, terraform/images/mp_image_ee_ucm.tfvars, terraform/images/mp_image_se_byol.tfvars, terraform/images/mp_image_suite_byol.tfvars, terraform/images/mp_image_suite_ucm.tfvars
=> Uptake 24.1.2 mp values.

terraform/images/mp_image_ee_byol.tfvars, terraform/images/mp_image_ee_ucm.tfvars, terraform/images/mp_image_se_byol.tfvars, terraform/images/mp_image_suite_byol.tfvars, terraform/images/mp_image_suite_ucm.tfvars, terraform/modules/compute/wls_compute/wls_compute.tf, terraform/modules/compute/wls_compute/wls_volume.tf
cherry pick Roberto's changes
uptake new image values.
=> Topic sk uptake cherry pick 24.1.2

terraform/modules/compute/wls_compute/wls_variables.tf
https://jira.oraclecorp.com/jira/browse/JCS-14385
=> Resolve review comment related to multi node provisioning mentioned in JCS-14385

terraform/images/mp_image_ee_byol.tfvars, terraform/images/mp_image_ee_ucm.tfvars, terraform/images/mp_image_se_byol.tfvars, terraform/images/mp_image_suite_byol.tfvars, terraform/images/mp_image_suite_ucm.tfvars
Uptake marketplace image values
(cherry picked from commit da2aef90ef3d09edefdc4c5788b360db8783d6df)
=> Uptake mp values. (#250)

terraform/locals.tf, terraform/main.tf, terraform/modules/compute/wls_compute/variables.tf, terraform/modules/compute/wls_compute/wls_compute.tf, terraform/schema.yaml, terraform/schema_14110.yaml, terraform/weblogic_variables.tf
https://jira.oraclecorp.com/jira/browse/JCS-14387
=> Ensure no boot.properties is on disk

terraform/images/mp_image_ee_byol.tfvars, terraform/images/mp_image_ee_ucm.tfvars, terraform/images/mp_image_se_byol.tfvars, terraform/images/mp_image_suite_byol.tfvars, terraform/images/mp_image_suite_ucm.tfvars, terraform/main.tf, terraform/modules/compute/wls_compute/variables.tf, terraform/modules/compute/wls_compute/wls_compute.tf, terraform/modules/validators/policy_validators.tf, terraform/modules/validators/variables.tf, terraform/variables.tf
cherry-pick from main to release branch
=> Topic sk release wlsoci24.2.1

terraform/data_sources.tf, terraform/locals.tf, terraform/main.tf, terraform/modules/compute/wls_compute/variables.tf, terraform/modules/compute/wls_compute/wls_compute.tf, terraform/modules/compute/wls_compute/wls_variables.tf, terraform/modules/lb/backends/variables.tf, terraform/modules/policies/locals.tf, terraform/modules/policies/variables.tf, terraform/modules/validators/validators.tf, terraform/modules/validators/variables.tf, terraform/schema.yaml, terraform/schema_14110.yaml, terraform/weblogic_variables.tf
https://jira.oraclecorp.com/jira/browse/JCS-14446
https://orahub.oci.oraclecorp.com/weblogic-cloud/wls-oci/-/merge_requests/1043
This MR includes the following fixes:
1. Removed variable wls_cluster_mc_port as its not being used in the code.
2. Fixed the certificate validity date
3. Removed SecuredExternAdmin channel with opens port 7002 from base-model-jrf-secure-mode.yaml & base-model-nonjrf-secure-mode.yaml
4. Changed secure production mode to secured production mode in the code at multiple places
=> topic_mb-JCS-14446

terraform/main.tf, terraform/modules/policies/locals.tf, terraform/modules/policies/variables.tf
https://jira.oraclecorp.com/jira/browse/JCS-14450
https://orahub.oci.oraclecorp.com/weblogic-cloud/wls-oci/-/merge_requests/1046
This MR includes:
1. Adding missing policy for wls_secondary_admin_password_id
2. Changing the policy for certificate authority from inspect -> read
=> Script to renew SSL certificate

terraform/modules/compute/wls_compute/variables.tf, terraform/modules/compute/wls_compute/wls_compute.tf
Add metadata for certificate OCID
https://jira.oraclecorp.com/jira/browse/JCS-14450
=> Add metadata for certificate OCID

terraform/main.tf, terraform/modules/policies/locals.tf, terraform/modules/policies/variables.tf
=> Changes in Auto-Scaling(Scale-In Scale-out) scripts required for secure production mode

terraform/modules/network-validator/scripts/network_validation.sh
**Testing**
1. Errors shown when no rules are added for Security Lists.
2. No errors, when all the required rules are added for Security Lists.
3. Errors shown when no rules are added for Network Security Groups.
4. No errors, when all the required rules are added for Network Security Groups.
=> Update network validation script

terraform/main.tf, terraform/modules/network/vcn-config/nsg_security_rule.tf, terraform/modules/network/vcn-config/variables.tf
This PR is to open managed server administration port in managed server nsg in secure mode
=> Open managed server administration port in managed server nsg

terraform/images/mp_image_ee_byol.tfvars, terraform/images/mp_image_ee_ucm.tfvars, terraform/images/mp_image_se_byol.tfvars, terraform/images/mp_image_suite_byol.tfvars, terraform/images/mp_image_suite_ucm.tfvars
=> Topic sk uptake mp 24.2.3

terraform/images/mp_image_ee_byol.tfvars, terraform/images/mp_image_ee_ucm.tfvars, terraform/images/mp_image_se_byol.tfvars, terraform/images/mp_image_suite_byol.tfvars, terraform/images/mp_image_suite_ucm.tfvars
=> Update 24.3.2 mp files.

terraform/images/mp_image_ee_byol.tfvars, terraform/images/mp_image_ee_ucm.tfvars, terraform/images/mp_image_se_byol.tfvars, terraform/images/mp_image_suite_byol.tfvars, terraform/images/mp_image_suite_ucm.tfvars
uptake oct psus to all 5 images
=> uptake oct psu

terraform/modules/policies/locals.tf
Set policies for enabling WLMS plugin
=> Set policies for enabling WLMS plugin

terraform/images/mp_image_ee_byol.tfvars, terraform/images/mp_image_ee_ucm.tfvars, terraform/images/mp_image_se_byol.tfvars, terraform/images/mp_image_suite_byol.tfvars, terraform/images/mp_image_suite_ucm.tfvars
PR for merging changes for 25.1.1 psu into development branch
=> uptake jan25 psu

terraform/images/mp_image_ee_byol.tfvars, terraform/images/mp_image_ee_ucm.tfvars, terraform/images/mp_image_se_byol.tfvars, terraform/images/mp_image_suite_byol.tfvars, terraform/images/mp_image_suite_ucm.tfvars
=> Uptake new 25.1.1 values.

terraform/modules/network-validator/scripts/network_validation.sh
Added check for egress rule to allow traffic in all ports in Managed Server Nsg.
=> Topic manvigup jcs 14691

terraform/images/mp_image_ee_byol.tfvars, terraform/images/mp_image_ee_ucm.tfvars, terraform/images/mp_image_se_byol.tfvars, terraform/images/mp_image_suite_byol.tfvars, terraform/images/mp_image_suite_ucm.tfvars
=> Uptake in reelase branch.

terraform/images/mp_image_ee_byol.tfvars, terraform/images/mp_image_ee_ucm.tfvars, terraform/images/mp_image_se_byol.tfvars, terraform/images/mp_image_suite_byol.tfvars, terraform/images/mp_image_suite_ucm.tfvars
Please review tfvars for Apr25 PSUS for publishing images to MarketPlace
=> Topic uptake apr25psus

terraform/modules/compute/wls_compute/idcs_variables.tf
Provisioning Succeeded 
Orahub MR : https://orahub.oci.oraclecorp.com/weblogic-cloud/wls-oci/-/merge_requests/1114
=> Uptake IDCS Appgateway 25.1.03-2501230623

terraform/images/mp_image_suite_byol.tfvars
=> Fix image.
